---
complexity:
  LongParameterList:
    ignoreDefaultParameters: true
    allowedFunctionParameters: 10
    allowedConstructorParameters: 10
  TooManyFunctions:
    allowedFunctionsPerObject: 20
    allowedFunctionsPerClass: 20
    allowedFunctionsPerInterface: 20
    allowedFunctionsPerFile: 20
    ignorePrivate: true
  LongMethod:
    allowedLines: 100
  CyclomaticComplexMethod:
    ignoreSingleWhenExpression: true
    allowedComplexity: 20

coroutines:
  SuspendFunSwallowedCancellation:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: false

naming:
  FunctionNaming:
    functionPattern: "[a-zA-Z][a-zA-Z0-9]*"
    excludeClassPattern: ".*Test$"

potential-bugs:
  ImplicitDefaultLocale:
    active: false

style:
  MaxLineLength:
    maxLineLength: 120
  MagicNumber:
    ignorePropertyDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotated:
      - "Preview"
      - "DesktopPreview"
      - "LandscapePreview"
      - "PortraitPreview"
    excludes:
      - "**/test/**"
      - "**/androidHostTest/**"
      - "**/jvmTest/**"
      - "**/commonTest/**"
  UnusedPrivateFunction:
    ignoreAnnotated:
      - "Preview"
      - "DesktopPreview"
      - "LandscapePreview"
      - "PortraitPreview"
      - "TabletPreview"
  ForbiddenComment:
    active: false
  ReturnCount:
    max: 5
