name: ktlint

on:
  push:
    paths:
      - "**.kt"
      - "**.kts"
      - "scripts/ktlint*"
      - ".run/ktlint*"

permissions:
  contents: read
  pull-requests: read

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Install
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.7.1/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/

      - name: Run
        run: scripts/ktlintCheck.sh
