name: ktlint

on:
  push:
    paths:
      - "**.kt"
      - "**.kts"
      - "scripts/ktlint*"
      - ".run/ktlint*"

permissions:
  contents: read
  pull-requests: read

jobs:
  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Install
        run: |
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/1.8.0/ktlint
          chmod a+x ktlint
          sudo mv ktlint /usr/local/bin/

      - name: Run
        run: scripts/ktlintCheck.sh
